
prp: ch7_fgets.o ch7_getline.o prp.o 
	$(CC) -o prp ch7_fgets.o ch7_getline.o prp.o

minscanf: minscanf_main.o minscanf.o
	$(CC) -o minscanf minscanf_main.o minscanf.o

clean:
	rm *.o

cleanprp:
	rm prp

cleanminscanf:
	rm minscanf
